[workspace]
name = "Iota"
resolver = "3"
members = [
    "src/bins/reflector",
    "src/libs/auth",
    "src/libs/crypto",
    "src/libs/db",
    "src/libs/error",
    "src/libs/gateway",
    "src/libs/utils",
]
