[package]
name = "iota_gui_client"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
iced = { version = "0.13.1", features = ["debug", "tokio"] }
log = "0.4.28"
tokio = { version = "1.47.1", features = ["full"] }
