[package]
name = "reflector"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
tokio = { version = "1.47.1", features = ["full"] }
envconfig = "0.11.0"
dotenv = "0.15.0"
lazy_static = "1.5.0"
env_logger = "0.11.8"
log = "0.4.27"
chrono = "0.4.41"
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "postgres",
    "chrono",
    "uuid",
] }
jsonwebtoken = "9.3.1"
serde = { version = "1.0", features = ["derive"] }
utoipa = { version = "5.2.0", features = ["chrono"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web", "vendored"] }
actix-cors = "0.7.0"

error = { path = "../../libs/error" }
db = { path = "../../libs/db" }
auth = { path = "../../libs/auth" }
utils = { path = "../../libs/utils" }
