[package]
name = "reflector"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
tokio = { version = "1.47.1", features = ["full"] }
envconfig = "0.11.0"
dotenv = "0.15.0"
lazy_static = "1.5.0"
env_logger = "0.11.8"

error = { path = "../../libs/error" }
db = { path = "../../libs/db" }
log = "0.4.27"
