[package]
name = "iota_desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32"
egui = "0.32"
egui_flex = "0.4.0"

egui_transition_animation = "0.1.6"
tokio = { version = "1.47.1", features = ["full"] }

hooks = { path = "../../libs/hooks" }
